### ISSUE TITLE
Feature Request: Adding link to license

### ISSUE THREAD

**Issue by thedark1337** [twada/licensify#10]
Most licenses being used should be SPDX compatible, using the [OpenSource Website] (https://opensource.org/licenses) along with the SPDX expression (For example GPL-3.0) would result in the following: https://opensource.org/licenses/GPL-3.0

I would like for in the comment tag to have a link to the license if it is a valid URL that can be obtained via a valid SPDX expression. (either once for all the same type of license or once per dependency)

Example:

```
/**
 * Modules in this bundle
 * @license
 * 
 * my-dependency:
 *   license: GPL-3.0 (https://opensource.org/licenses/GPL-3.0)
 *   author: Thedark1337 <thedark1337@thedark1337.com> (https://thedark1337.com/)
 *   version: 1.0.0
 * This header is generated by licensify (https://github.com/twada/licensify)
 **/
```

**Comment by twada** [comment]
@thedark1337 Thank you for your feature request! Nice feature :)

**Comment by twada** [comment]
[licensify 2.2.0](https://github.com/twada/licensify/blob/master/CHANGELOG.md#220-2016-02-01) is out. Thank you for your feature request!

**Comment by thedark1337** [comment]
Thank you for your fast response time :+1:
